# Extends the mainnet preset
PRESET_BASE: mainnet
CONFIG_NAME: ephemery # required by Prysm, prevents conflict with mainnet genesis

# Genesis
# ---------------------------------------------------------------
# Minimum number of active validators to start the chain
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 64
# Genesis Zero; must be overridden per iteration
MIN_GENESIS_TIME: 1393527600
# Seconds after eth1 timestamp to start the beacon chain
GENESIS_DELAY: 600
GENESIS_FORK_VERSION: 0x1000101b

# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

ALTAIR_FORK_VERSION: 0x2000101b
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x3000101b
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x4000101b
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x5000101b
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_VERSION: 0x6000101b
ELECTRA_FORK_EPOCH: 0
FULU_FORK_VERSION: 0x7000101b
FULU_FORK_EPOCH: 0 

# Time parameters
# ---------------------------------------------------------------
SECONDS_PER_SLOT: 12
SECONDS_PER_ETH1_BLOCK: 12
ETH1_FOLLOW_DISTANCE: 12
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
# The period of time after which the network resets
EPHEMERY_RESET_PERIOD: 2419200

# Validator cycle
# ---------------------------------------------------------------
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 30000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 65536
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 8

# Fork choice
# ---------------------------------------------------------------
PROPOSER_SCORE_BOOST: 40
REORG_HEAD_WEIGHT_THRESHOLD: 20
REORG_PARENT_WEIGHT_THRESHOLD: 160
REORG_MAX_EPOCHS_SINCE_FINALIZATION: 2

# Deposit contract
# ---------------------------------------------------------------
# Genesis Zero chain ID; must be overridden per iteration
DEPOSIT_CHAIN_ID: 39438000 
# Genesis Zero network ID; must be overridden per iteration
DEPOSIT_NETWORK_ID: 39438000 
DEPOSIT_CONTRACT_ADDRESS: 0x00000000219ab540356cBB839Cbe05303d7705Fa

# Networking
# ---------------------------------------------------------------
MAX_PAYLOAD_SIZE: 10485760
MAX_REQUEST_BLOCKS: 1024
EPOCHS_PER_SUBNET_SUBSCRIPTION: 256
MIN_EPOCHS_FOR_BLOCK_REQUESTS: 33024
TTFB_TIMEOUT: 5
RESP_TIMEOUT: 10
ATTESTATION_PROPAGATION_SLOT_RANGE: 32
MAXIMUM_GOSSIP_CLOCK_DISPARITY: 500
MESSAGE_DOMAIN_INVALID_SNAPPY: 0x00000000
MESSAGE_DOMAIN_VALID_SNAPPY: 0x01000000
SUBNETS_PER_NODE: 2
ATTESTATION_SUBNET_COUNT: 64
ATTESTATION_SUBNET_EXTRA_BITS: 0
ATTESTATION_SUBNET_PREFIX_BITS: 6

# Deneb
# ---------------------------------------------------------------
MAX_REQUEST_BLOCKS_DENEB: 128
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 4096
BLOB_SIDECAR_SUBNET_COUNT: 6
MAX_BLOBS_PER_BLOCK: 6
MAX_REQUEST_BLOB_SIDECARS: 768

# Electra
# ---------------------------------------------------------------
MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA: 128000000000
MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT: 256000000000
BLOB_SIDECAR_SUBNET_COUNT_ELECTRA: 9
MAX_BLOBS_PER_BLOCK_ELECTRA: 9
# MAX_REQUEST_BLOCKS_DENEB * MAX_BLOBS_PER_BLOCK_ELECTRA
MAX_REQUEST_BLOB_SIDECARS_ELECTRA: 1152

# Fulu
# ---------------------------------------------------------------
NUMBER_OF_COLUMNS: 128
NUMBER_OF_CUSTODY_GROUPS: 128
DATA_COLUMN_SIDECAR_SUBNET_COUNT: 128
MAX_REQUEST_DATA_COLUMN_SIDECARS: 16384
SAMPLES_PER_SLOT: 8
CUSTODY_REQUIREMENT: 4
VALIDATOR_CUSTODY_REQUIREMENT: 8
BALANCE_PER_ADDITIONAL_CUSTODY_GROUP: 32000000000
MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS: 4096

# Blob Scheduling
# ---------------------------------------------------------------
BLOB_SCHEDULE:
  - EPOCH: 2048
    MAX_BLOBS_PER_BLOCK: 15
  - EPOCH: 4096
    MAX_BLOBS_PER_BLOCK: 21
